### ISSUE TITLE
META microdata in content breaks loading

### ISSUE THREAD

**Issue by kiogo** [miguel-perez/smoothState.js#105] opened 2014-10-29 13:49 UTC
Hello,

I have content that contains the following microdata:

`<div itemprop='video' itemscope itemtype='http://schema.org/VideoObject'>`
`<meta itemprop='name' content=''>`
`<meta itemprop='description' content=''>`
`<meta itemprop='duration' content=''>`
`<meta itemprop='thumbnailURL' content=''>`
`<meta itemprop='embedURL' content=''>`
`</div>`
`<div>the rest of my content...</div>`

When smoothState loads these pages, only the div with the first meta tag loads:

`<div itemprop='video' itemscope itemtype='http://schema.org/VideoObject'>`
`<meta itemprop='name' content='$title'>`
`</div>`

If I remove the meta tags, then the content loads fine. Any ideas?

Thanks

**Comment by miguel-perez** [comment] 2015-05-23 17:56
@kiogo has @johanneslamers's suggestion work out for you? Let me know.

**Comment by miguel-perez** [comment] 2015-05-28 11:31
This is by far the most bizarre bug I've ever seen, ever. lol. It comes down to this, if the document body has two meta tags, like so:

``` html
<meta />
<meta />
```

The thing just chokes and dies. I'll keep working on it and try to find the root cause. Thanks for the report.

**Comment by miguel-perez** [comment] 2015-05-28 21:21
So I replaced a bunch of jQuery nonsense with some vanilla js and saved us about 150 lines of code and some speed. Most importantly, this bug should be fixed.

@kiogo,  @johanneslamers, please let me know if this works out. Closing for now, but let me know if you see anything odd and I'll open it back up.

**Closed by miguel-perez** 2015-05-28 21:21 UTC
Labels: bug
