### ISSUE TITLE
Clunky transitions on slow connection speeds

### ISSUE THREAD

**Issue by ryanwake01** [miguel-perez/smoothState.js#156] opened 2015-04-17 02:42 UTC
My client is experiencing very clunky transitions on page loads. I suspect this is a caching issue, so I am wondering if there you have a suggestion for how we could remedy this. I see there is a caching option in the documentation, so I am wondering if this will help remedy this issue. You can see the site in question at: http://bobby.gramacy.com/

**Comment by ryanwake01** [comment] 2015-05-13 16:17
Anyone? I went ahead and implemented the pagecaching and I am still seeing the same issues. Anyone have some kind of insight into this? Something we are doing wrong? or is there a bug with this plugin?

**Comment by miguel-perez** [comment] 2015-05-13 16:21
@ryanwake01 Could you update this issue with some [more detail](https://github.com/miguel-perez/smoothState.js#how-to-ask-for-help) on the problem? Knowing, for example, what browsers your using and how to reproduce the clunky animations would help us troubleshoot.

**Comment by ryanwake01** [comment] 2015-05-13 16:28
We are using Chrome. However, I am seeing the same issues regardless of browser. 

The problem is that sometimes you click on a link, and rather than transitioning to the new page it slides in the old one instead.  And then it often hangs a little and finally swaps in the new one.  Sometimes it never swaps in the new one. The slide effect is always smooth, it's just the links are problematic. I would even be willing to send you the source code via email if that would help. I would like to use this plugin on other projects, but I need to understand if I am doing something that is causing this, or if I am just not implementing it as it is intended.

**Comment by ryanwake01** [comment] 2015-05-13 16:37
I am also noticing that the client added some images to a couple pages that seem to be broken - I am getting a 404 error on those pages for the images. I am wondering if that might cause a problem as well.

**Comment by miguel-perez** [comment] 2015-05-13 16:42
@ryanwake01 It's not as easy as it might seem to replicate the issues you're having on my end. You've been dealing with the error for a while now, so you know it like the back of your hand, but others don't. I clicked around the site on Chrome without noticing any issues.

Please take the time to fill out the questions described in the [guidelines](https://github.com/miguel-perez/smoothState.js#how-to-ask-for-help). Things like steps to reproduce, version of smoothState, and a solid description of the error will help a ton.

**Comment by ryanwake01** [comment] 2015-05-13 17:12
**smoothState.js version tested:**
- unsure what version
  - also using: jquery 1.11.1, bootstrap v3.0, modernizr.js

**Browser versions or Packager version tested against:**
- Chrome
- Safari
  - Firefox

**Description:**
- Chrome & Safari: Click on a link and rather than transitioning to the new page it slides in the old one instead. And then it often hangs a little and finally swaps in the new one 
- Firefox: There does not seem to have a slide out effect - unlike Chrome and Safari

**Steps to reproduce the problem:**
- Just clicking on different stuff seems to work - prior to an caching taking affect. 

Examples:
Here are some videos showing the issues I am seeing: 
Chrome: https://www.dropbox.com/s/ehm53yreso02c9e/chrome_glitch.mov?dl=0
Firefox: https://www.dropbox.com/s/6b5vg7ixtoqjs2q/firefox_glitch.mov?dl=0

**Comment by miguel-perez** [comment] 2015-05-20 11:34
I tracked it down to the issue being with latency. I was having trouble reproducing this in any of my browsers until I started to simulate some slower internet connections.

It seems like the "is-exiting" class is being removed from the container too early, before the page is loaded, so it pops back into place. Not entirely sure what the solution here is, yet, but I'll keep tinkering and let you know what I find.

**Comment by miguel-perez** [comment] 2015-05-20 11:56
I just confirmed that this is a bug with smoothState itself. Looks like it doesn't do much to take into account slower internet speeds. I'll work on patching this asap. In the meantime, I've got a work around for you.

I see that you're comfortable with prefetching and caching, yay! So, what we can do here is prefetch all the pages in advance using the [fetch method](https://github.com/miguel-perez/smoothState.js#fetchurl). Maybe something like:

``` js
var $smooth = $('#main').data('smoothState');
$('#gramacy_nav a').each(function(i, el){ 
  if(!$.smoothStateUtility.isExternal(el.href)) {
    $smooth.fetch(el.href);
  }
});
```

Hope that helps! And sorry about having to deal with this so long.

**Comment by erbridge** [comment] 2015-05-26 16:14
This one's hitting me too, especially on mobile. It would be great to see a fix.

**Comment by miguel-perez** [comment] 2015-05-26 19:03
@ryanwake01 @erbridge I've provided a fix for this in the form of a new method for restarting css animations. See the [restartCSSAnimations()](https://github.com/miguel-perez/smoothState.js#restartcssanimations) and the notes I've added on [toggleAnimationClass](https://github.com/miguel-perez/smoothState.js#toggleanimationclassclassname).

Let me know if this works out for you.

**Closed as completed** 2015-05-26 20:48 UTC
Labels: bug

**Comment by erbridge** [comment] 2015-05-26 22:30
This is a much better experience now. Thanks!

**Comment by ryanwake01** [comment] 2015-07-08 18:25
Miguel, 

I had to step away from this for a little while... I am now back to looking into getting this fixed. How would I go about implementing this new method of restartCSSAnimations();

Currently, this is what I am using:

```
;(function ($) {
    'use strict';
    var $body    = $('html, body'),
        content  = $('#main').smoothState({
            prefetch: true,
            async: true,
            pageCacheSize: 15,
            onStart: {
                duration: 500,
                render: function (url, $container) {
                    content.toggleAnimationClass('is-exiting');
                    // $body.animate({
                    //     scrollTop: 0
                    // });
                }
            }
        }).data('smoothState');
})(jQuery);
```

**Comment by miguel-perez** [comment] 2015-07-08 18:35
@ryanwake01 see the demo: https://github.com/miguel-perez/smoothState.js/blob/master/demos/csstricks/functions.js

**Comment by ryanwake01** [comment] 2015-07-08 19:48
I figured it out. Another newb mistake... Thank you for your help. Again!
